# Библиотека NumPy

Выполняйте задания прямо в этом блокноте. При необходимости, можете создавать новые ячейки для кода или текста.

# После этой ячейки обязательно сделайте ещё одну Markdown ячейку, в которой напишите своё ФИО и номер группы, а также соответствующим образом назовите файл!

## Задание 1: Изучение массивов NumPy

### 1. Создание массива и его свойства.
Создайте одномерный массив NumPy из списка Python и двумерный массив из списка списков.
Выведите форму, размер и тип данных этих массивов.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

python_list = list(range(1000))
numpy_array = np.array(range(1000))

python_result = [x*2 for x in python_list]
numpy_result = numpy_array*2

print("Python list result:", python_result[:10])  # Print first 10 results
print("NumPy array result:", numpy_result[:10])  # Print first 10 results


Python list result: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
NumPy array result: [ 0  2  4  6  8 10 12 14 16 18]


### 2. Индексирование и разрезание массивов.
Получите доступа к определенным элементам, строкам и столбцам двумерного массива.
Создайте подмассив с помощью среза и измените его элемент.

In [39]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

print("Original array:", arr)

print("Sliced array:", arr[:, 2:5])  # Slicing to get columns 2 to 4
print("Sliced array:", arr[-3:]) # Slicing to get last 3 rows
print("С пяти до восьми:", arr[:, 4:8])  # Slicing to get columns 4 to 7

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                      [7, 8, 9]])


print("Original matrix:\n", matrix)

print("Первые две строки:\n", matrix[:2, :])  # First two rows
print("Последние две строки:\n", matrix[-2:, :])  # Last two rows
print("Последние два столбца:\n", matrix[:, -2:])  # Last two columns
print("Каждый второй столбец и каждая вторая строка:\n", matrix[::2, ::2])  # Every second row and column

sub_arr = arr[0, 2:5]  # Extracting a sub-array from the first row, columns 2 to 4
mask_sub_arr = sub_arr > 4  # Creating a boolean mask for values greater than 4
print("sub_arr:", sub_arr)
print("mask_sub_arr:", sub_arr[mask_sub_arr])  # Applying the mask to get values greater than 4


Original array: [[1 2 3 4 5 6 7 8 9]]
Sliced array: [[3 4 5]]
Sliced array: [[1 2 3 4 5 6 7 8 9]]
С пяти до восьми: [[5 6 7 8]]
Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Первые две строки:
 [[1 2 3]
 [4 5 6]]
Последние две строки:
 [[4 5 6]
 [7 8 9]]
Последние два столбца:
 [[2 3]
 [5 6]
 [8 9]]
Каждый второй столбец и каждая вторая строка:
 [[1 3]
 [7 9]]
sub_arr: [3 4 5]
mask_sub_arr: [5]


### 3. Операции с массивами.
Выполните поэлементное сложение, вычитание, умножение и деление в массивах.

In [ ]:
arr1 =  np.array([[1, 2, 3]])
arr2 =  np.array([[4, 5, 6]])

print(arr1 * arr2)

matrix1 = np.array([[1, 2],
                    [3, 4]])
vector = np.array([[1, 2]])
print(matrix1+vector)  # Matrix + operation

print("Матричные корни:\n", np.sqrt(matrix1))  # Square root of the matrix
print("Матричные экспоненты:\n", np.exp(matrix1))  # Exponential of the matrix

[[ 4 10 18]]
[[2 4]
 [4 6]]


### 4. Переформирование и конкатенация.
Перестройте двумерный массив в другую форму (например, из 4x3 в 3x4).

In [ ]:
# ваш код здесь

## Задание 2: Случайные числа и статистический анализ

### 1. Генерация случайных чисел.
Сгенерируйте одномерный массив из 100 случайных чисел с помощью NumPy `random.rand`.
Создайте двумерный массив случайных целых чисел заданной формы с помощью NumPy [`random.randint`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html).

In [ ]:
# ваш код здесь

### 2. Статистический анализ.
Вычислите и выведите среднее значение, медиану и стандартное отклонение сгенерированных массивов.
Найдите минимальное и максимальное значения в массивах.

In [ ]:
# ваш код здесь

## Задание 3: Продвинутые операции с массивами NumPy

### 1. Матричные операции.
Создайте две матрицы заданной размерности.
Выполняйте сложение, вычитание и умножение матриц.

In [ ]:
# ваш код здесь

Создайте два или более массивов и выполните операции соединения (горизонтальное и вертикальное) с помощью указания параметра `axis` у метода `concatenate`. Измените форму одного из массивов с помощью `reshape`.

In [ ]:
# ваш код здесь

### 2. Булевы операции.
Примените булевы операции к массиву.

In [ ]:
# ваш код здесь