# Библиотека NumPy

Выполняйте задания прямо в этом блокноте. При необходимости, можете создавать новые ячейки для кода или текста.

# После этой ячейки обязательно сделайте ещё одну Markdown ячейку, в которой напишите своё ФИО и номер группы, а также соответствующим образом назовите файл!

## Задание 1: Изучение массивов NumPy

### 1. Создание массива и его свойства.
Создайте одномерный массив NumPy из списка Python и двумерный массив из списка списков.
Выведите форму, размер и тип данных этих массивов.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

python_list = list(range(1000))
numpy_array = np.array(range(1000))

python_result = [x*2 for x in python_list]
numpy_result = numpy_array*2

print("Python list result:", python_result[:10])  # Print first 10 results
print("NumPy array result:", numpy_result[:10])  # Print first 10 results


Python list result: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
NumPy array result: [ 0  2  4  6  8 10 12 14 16 18]


### 2. Индексирование и разрезание массивов.
Получите доступа к определенным элементам, строкам и столбцам двумерного массива.
Создайте подмассив с помощью среза и измените его элемент.

In [39]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

print("Original array:", arr)

print("Sliced array:", arr[:, 2:5])  # Slicing to get columns 2 to 4
print("Sliced array:", arr[-3:]) # Slicing to get last 3 rows
print("С пяти до восьми:", arr[:, 4:8])  # Slicing to get columns 4 to 7

matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                      [7, 8, 9]])


print("Original matrix:\n", matrix)

print("Первые две строки:\n", matrix[:2, :])  # First two rows
print("Последние две строки:\n", matrix[-2:, :])  # Last two rows
print("Последние два столбца:\n", matrix[:, -2:])  # Last two columns
print("Каждый второй столбец и каждая вторая строка:\n", matrix[::2, ::2])  # Every second row and column

sub_arr = arr[0, 2:5]  # Extracting a sub-array from the first row, columns 2 to 4
mask_sub_arr = sub_arr > 4  # Creating a boolean mask for values greater than 4
print("sub_arr:", sub_arr)
print("mask_sub_arr:", sub_arr[mask_sub_arr])  # Applying the mask to get values greater than 4


Original array: [[1 2 3 4 5 6 7 8 9]]
Sliced array: [[3 4 5]]
Sliced array: [[1 2 3 4 5 6 7 8 9]]
С пяти до восьми: [[5 6 7 8]]
Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Первые две строки:
 [[1 2 3]
 [4 5 6]]
Последние две строки:
 [[4 5 6]
 [7 8 9]]
Последние два столбца:
 [[2 3]
 [5 6]
 [8 9]]
Каждый второй столбец и каждая вторая строка:
 [[1 3]
 [7 9]]
sub_arr: [3 4 5]
mask_sub_arr: [5]


### 3. Операции с массивами.
Выполните поэлементное сложение, вычитание, умножение и деление в массивах.

In [45]:
arr1 =  np.array([[1, 2, 3]])
arr2 =  np.array([[4, 5, 6]])

print(arr1 * arr2)

matrix1 = np.array([[1, 2],
                    [3, 4]])
vector = np.array([[1, 2]])
print(matrix1+vector)  # Matrix + operation

print("Матричные корни:\n", np.sqrt(matrix1))  # Square root of the matrix
print("Матричные экспоненты:\n", np.exp(matrix1))  # Exponential of the matrix

[[ 4 10 18]]
[[2 4]
 [4 6]]
Матричные корни:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
Матричные экспоненты:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


### 4. Переформирование и конкатенация.
Перестройте двумерный массив в другую форму (например, из 4x3 в 3x4).

In [ ]:
# ваш код здесь

## Задание 2: Случайные числа и статистический анализ

### 1. Генерация случайных чисел.
Сгенерируйте одномерный массив из 100 случайных чисел с помощью NumPy `random.rand`.
Создайте двумерный массив случайных целых чисел заданной формы с помощью NumPy [`random.randint`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html).

In [ ]:
# ваш код здесь

### 2. Статистический анализ.
Вычислите и выведите среднее значение, медиану и стандартное отклонение сгенерированных массивов.
Найдите минимальное и максимальное значения в массивах.

In [ ]:
# ваш код здесь

## Задание 3: Продвинутые операции с массивами NumPy

### 1. Матричные операции.
Создайте две матрицы заданной размерности.
Выполняйте сложение, вычитание и умножение матриц.

In [55]:
data1 = np.random.randn(10, 3)  # Generating random data with 100 rows and 3 columns
data2 = np.random.randn(10, 3)  # Generating another set of random data with the same shape

summ = data1 + data2  # Element-wise addition of the two datasets
razn = data1 - data2  # Element-wise subtraction of the two datasets
multiplication = data1 * data2  # Element-wise multiplication of the two datasets

print("Сумма:\n", summ)
print("Разность:\n", razn)
print("Произведение:\n", multiplication)

Сумма:
 [[-3.88484186 -0.77059987 -0.89208143]
 [ 2.42196678  1.30867817 -1.77247867]
 [ 0.4435091   0.591795   -1.56817546]
 [ 0.93663076  0.5724325  -1.87379526]
 [-0.19130804 -1.08117407 -0.32689877]
 [-0.41489879  1.26547246 -0.60664379]
 [ 1.16966941 -0.54650357  0.62775509]
 [-1.05300844 -0.60732706  0.32872814]
 [ 2.01397905 -1.37634865 -1.25605021]
 [-0.57961892 -0.68638728  0.54287891]]
Разность:
 [[ 1.46284498 -2.11844779 -1.90459927]
 [ 0.06340397 -2.27247638 -0.79890089]
 [ 0.3902397   0.41918852 -2.84898975]
 [-0.59538785 -1.00329257  0.42736696]
 [ 0.80196524 -0.24146147  0.03288001]
 [-0.88450007  0.86231815  1.94361113]
 [-0.359304    1.7072969   0.98034018]
 [ 0.78734202  1.45910006 -1.12472368]
 [-0.16250384 -0.84094848  0.28216909]
 [-0.30388032 -0.47198234  0.84615301]]
Произведение:
 [[ 3.23802022 -0.97349923 -0.70792228]
 [ 1.46547575 -0.86287759  0.6258595 ]
 [ 0.01110333  0.04362558 -1.41439208]
 [ 0.13069762 -0.16972926  0.83211653]
 [-0.15163737  0.27765843  0

Создайте два или более массивов и выполните операции соединения (горизонтальное и вертикальное) с помощью указания параметра `axis` у метода `concatenate`. Измените форму одного из массивов с помощью `reshape`.

In [61]:
arr = np.arange(12)
matrix = arr.reshape(3, 4)  # Reshaping the array into a 3x4 matrix
print("Original array:", arr)
print("Reshaped matrix:\n", matrix)

print("Transposed matrix:\n", matrix.T)  # Transposing the matrix

arr1 = np.array([[1, 2,], 
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

combined = np.concatenate((arr1, arr2), axis=0)  # Concatenating along rows
print("Combined array:\n", combined)
combined_axis1 = np.concatenate((arr1, arr2), axis=1)  # Concatenating along columns
print("Combined array along axis 1:\n", combined_axis1)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposed matrix:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Combined array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Combined array along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


### 2. Булевы операции.
Примените булевы операции к массиву.

In [ ]:
# ваш код здесь