# Практическая работа №1
### Тема: Использование библиотеки NumPy

**Студент:** Повх Иван Олегович 
**Группа:** 3ИСИП624

---

## Задание 1. Настройка окружения
Импортируйте библиотеку `numpy` под стандартным алиасом `np`.

In [104]:
# Ваш код здесь
import numpy as np

## Задание 2. Создание массивов
Создайте три массива:
1. Одномерный массив (`n1`)
2. Двухмерный массив (`n2`)
3. Трёхмерный массив (`n3`)

In [105]:
# Ваш код здесь
n1 = np.array([1, 2, 3])
n2 = np.array([[1, 2],
               [2, 3]])
n3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(n1)
print(n2)
print(n3)

[1 2 3]
[[1 2]
 [2 3]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Задание 3. Изучение свойств массивов
Для каждого из созданных массивов (`n1`, `n2`, `n3`) выведите на экран следующие свойства:
* Количество измерений (`.ndim`)
* Размерность / форма (`.shape`)
* Тип данных (`.dtype`)
* Общее количество элементов (`.size`)

In [106]:
def element (x):
    print(np.ndim(x))
    print(np.shape(x))
    print(x.dtype)
    print(np.size(x))


element(n1)
element(n2)
element(n3)

1
(3,)
int64
3
2
(2, 2)
int64
4
3
(2, 2, 2)
int64
8


## Задание 4. Математические операции с числами
С каждым из трёх массивов выполните базовые арифметические операции с любым числом:
* Сложение
* Вычитание
* Умножение
* Деление

In [107]:
# Ваш код здесь
def math (x):
    print(x - 1)
    print(x + 1)
    print(x * 2)
    print(x / 2)


math(n1)
math(n2)
math(n3)

[0 1 2]
[2 3 4]
[2 4 6]
[0.5 1.  1.5]
[[0 1]
 [1 2]]
[[2 3]
 [3 4]]
[[2 4]
 [4 6]]
[[0.5 1. ]
 [1.  1.5]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]
[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]
[[[0.5 1. ]
  [1.5 2. ]]

 [[2.5 3. ]
  [3.5 4. ]]]


## Задание 5. Операции между массивами
1. Создайте копию вашего двухмерного массива `n2` с помощью метода `.copy()`.
2. Создайте новый двухмерный массив такого же размера.
3. Выполните с ними математические операции: сложение, вычитание, умножение и деление массивов.

In [108]:
def copy_math(x):

    x_copy = np.copy(x)

    x_work = np.array([[1, 2 ,3 ],
                          [4, 8 ,9]])

    print("Вычитание:\n", x_copy - x_work)
    print("Сложение:\n", x_copy + x_work)
    print("Умножение:\n", x_copy * x_work)
    print("Деление:\n", x_copy / x_work)

n2 = np.array([[5, 10, 15],
               [20, 25, 30]])
copy_math(n2)

Вычитание:
 [[ 4  8 12]
 [16 17 21]]
Сложение:
 [[ 6 12 18]
 [24 33 39]]
Умножение:
 [[  5  20  45]
 [ 80 200 270]]
Деление:
 [[5.         5.         5.        ]
 [5.         3.125      3.33333333]]


## Задание 6. Объединение массивов
Используя два двухмерных массива из предыдущего задания, выполните их объединение с помощью функции `np.concatenate()` с указанием параметра `axis`.

In [109]:
def obsh (x):

    x_work = np.array([[1, 2 ,3 ],
                          [4, 8 ,9]])
    
    obsh = np.concatenate((x, x_work), axis=1)
    print(obsh)


obsh(n2)

[[ 5 10 15  1  2  3]
 [20 25 30  4  8  9]]


## Задание 7. Тригонометрические функции
Создайте новый массив из случайных чисел и вычислите для его элементов косинус, синус и тангенс.

In [110]:
# Ваш код здесь

def trig (x):
    angles_rad = np.radians(x)
    angels_sin = np.sin(angles_rad)
    angels_con = np.cos(angles_rad)
    anglets_tg = np.tan(angles_rad)

    print("Радианы:\n", angles_rad)
    print("Синусы:\n", angels_sin)
    print("Косинусы:\n", angels_con)
    print("Тангенсы:\n", anglets_tg )

angles_deg = np.array([0, 30, 45, 60, 90])
trig(angles_deg)

Радианы:
 [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Синусы:
 [0.         0.5        0.70710678 0.8660254  1.        ]
Косинусы:
 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Тангенсы:
 [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


## Задание 8. Булевы выражения
Примените два любых булевых выражения к массиву из случайных чисел.

In [111]:
rng = np.random.default_rng()

df_rng = rng.integers(low = 10, high = 100, size = (3, 4))

mask1 = (df_rng > 15)
mask2 = (df_rng < 30)
print(mask1)
print(mask2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [ True False False  True]
 [False  True False False]]


## Задание 9. Работа со срезами (Slicing)
Поэкспериментируйте со срезами: выведите первую строку массива, первый столбец массива и выбранный диапазон.

In [115]:
# Ваш код здесь
x_work = np.array([[1, 2 ,3 ],
                    [4, 8 ,9]])

first = x_work[:1, :]
second = x_work[:, 0]

diap = x_work[:5]

print(first)
print(second)
print(diap)

[[1 2 3]]
[1 4]
[[1 2 3]
 [4 8 9]]
